In [1]:
import pandas as pd
import numpy as np

In [19]:
d=np.arange(1,21).reshape(5,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [8]:
df=pd.DataFrame(data=d,index=[1,2,3,4,5],columns=['vivek','sankalp','tushar','shreyash'])
df

   vivek  sankalp  tushar  shreyash
1      1        2       3         4
2      5        6       7         8
3      9       10      11        12
4     13       14      15        16
5     17       18      19        20

In [14]:
df.head(3)
df.tail(3)

   vivek  sankalp  tushar  shreyash
3      9       10      11        12
4     13       14      15        16
5     17       18      19        20

In [15]:
type(df)

pandas.DataFrame

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, 1 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   vivek     5 non-null      int64
 1   sankalp   5 non-null      int64
 2   tushar    5 non-null      int64
 3   shreyash  5 non-null      int64
dtypes: int64(4)
memory usage: 200.0 bytes

In [20]:
df.describe()

           vivek    sankalp     tushar   shreyash
count   5.000000   5.000000   5.000000   5.000000
mean    9.000000  10.000000  11.000000  12.000000
std     6.324555   6.324555   6.324555   6.324555
min     1.000000   2.000000   3.000000   4.000000
25%     5.000000   6.000000   7.000000   8.000000
50%     9.000000  10.000000  11.000000  12.000000
75%    13.000000  14.000000  15.000000  16.000000
max    17.000000  18.000000  19.000000  20.000000

In [21]:
df.head()

   vivek  sankalp  tushar  shreyash
1      1        2       3         4
2      5        6       7         8
3      9       10      11        12
4     13       14      15        16
5     17       18      19        20

In [22]:
df['vivek']

1     1
2     5
3     9
4    13
5    17
Name: vivek, dtype: int64

In [37]:
#for column simple weite column name direct
df[['sankalp','tushar']]

   sankalp  tushar
1        2       3
2        6       7
3       10      11
4       14      15
5       18      19

In [38]:
#loc word is used for show row index
df.loc[[2,3,4]]

   vivek  sankalp  tushar  shreyash
2      5        6       7         8
3      9       10      11        12
4     13       14      15        16

In [40]:
df.head()

   vivek  sankalp  tushar  shreyash
1      1        2       3         4
2      5        6       7         8
3      9       10      11        12
4     13       14      15        16
5     17       18      19        20

In [42]:
#iloc is usde for row and column combination
df.iloc[1:3,0:2]

   vivek  sankalp
2      5        6
3      9       10

In [47]:
df.iloc[::4,::3]

   vivek  shreyash
1      1         4
5     17        20

In [50]:
df

   vivek  sankalp  tushar  shreyash
1      1        2       3         4
2      5        6       7         8
3      9       10      11        12
4     13       14      15        16
5     17       18      19        20

In [49]:
#for converting data frame into array use .values
df.values

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [53]:
#basics operations in pandas
df.isnull().sum()

vivek       0
sankalp     0
tushar      0
shreyash    0
dtype: int64

In [ ]:
#these is give total count present how many time any number in data set
df['vivek'].value_counts()

vivek
1     1
5     1
9     1
13    1
17    1
Name: count, dtype: int64

In [61]:
#unique shows how many unique numbers in data set
df['vivek'].unique()

array([ 1,  5,  9, 13, 17])