### Tutorial 10- Python Pandas Tutorials- Part 2

In Part we are going to learn about
1. StringIO
2. Pandas read_csv

In [6]:
### Reading Different Data sources with the help of pandas
from io import StringIO

In [7]:
import pandas as pd
df=pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
type(df)

pandas.DataFrame

In [9]:
data=('col1,col2,col3\n'
     'x,y,1\n'
     'a,b,2\n'
     'c,d,3')

In [10]:
type(data)

str

In [11]:
##in memeory file format object
StringIO(data)

In [12]:
pd.read_csv(StringIO(data))

  col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [13]:
pd.read_csv(StringIO(data),usecols=['col1','col2'])

  col1 col2
0    x    y
1    a    b
2    c    d

In [14]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
import pandas as pd
df=pd.read_csv('train.csv',usecols=['Sex','Age','Cabin','Ticket','Name','Fare'])
df.head()

,Name,Sex,Age,Ticket,Fare,Cabin
0,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85
2,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123
4,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN

In [ ]:
df.to_csv('test.csv',index=False)

In [ ]:
##datatypes in csv
data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11')

In [ ]:
df=pd.read_csv(StringIO(data))

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
 3   d       2 non-null      float64
dtypes: float64(1), int64(3)
memory usage: 224.0 bytes

In [ ]:
df=pd.read_csv(StringIO(data),dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      object
 1   b       3 non-null      object
 2   c       3 non-null      object
 3   d       2 non-null      object
dtypes: object(4)
memory usage: 224.0+ bytes

In [ ]:
df.head()

   a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN

In [ ]:
df.isnull().sum()

a    0
b    0
c    0
d    1
dtype: int64

In [ ]:
df['a'][0]

1

In [ ]:
##datatypes in csv
data = ('a,b,c,d\n'
            '1,2,3,4\n'
            '5,6,7,8\n'
            '9,10,11')

In [ ]:
df=pd.read_csv(StringIO(data),dtype={'a':int,'b':float,'c':int})

In [ ]:
df

   a     b   c    d
0  1   2.0   3  4.0
1  5   6.0   7  8.0
2  9  10.0  11  NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int32
 1   b       3 non-null      float64
 2   c       3 non-null      int32
 3   d       2 non-null      float64
dtypes: float64(2), int32(2)
memory usage: 200.0 bytes

In [ ]:
df.dtypes

a      int32
b    float64
c      int32
d    float64
dtype: object

In [ ]:
data = ('index,a,b,c\n'
           '4,apple,bat,5.7\n'
            '8,orange,cow,10')

In [ ]:
pd.read_csv(StringIO(data),index_col=0)

            a    b     c
index
4       apple  bat   5.7
8      orange  cow  10.0

In [ ]:
# use index cols and usecols
data = ('a,b,c\n'
           '4,apple,bat\n'
            '8,orange,cow')

In [ ]:
pd.read_csv(StringIO(data),usecols=['a','b','c'],index_col=0)

        b    c
a
4   apple  bat
8  orange  cow

In [17]:
pd.read_csv('cu.item',sep='\t')

,item_code,item_name,display_level,selectable,sort_sequence
0,AA0,All items - old base,0,T,2
1,AA0R,Purchasing power of the consumer dollar - old ...,0,T,400
2,SA0,All items,0,T,1
3,SA0E,Energy,1,T,375
4,SA0L1,All items less food,1,T,359
...,...,...,...,...,...
395,SSEA011,College textbooks,3,T,314
396,SSEE041,Smartphones,4,T,335
397,SSFV031A,Food at elementary and secondary schools,3,T,122
398,SSGE013,Infants' equipment,3,T,356
399,SSHJ031,Infants' furniture,3,T,165